// <auto-generated />
using JUYEONG_WEB_APPLICATION;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JUYEONG_WEB_APPLICATION.Migrations.CalendarEventInfoDb
{
    [DbContext(typeof(CalendarEventInfoDbContext))]
    partial class CalendarEventInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JUYEONG_WEB_APPLICATION.CalendarEventInfo", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Start")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("End")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title", "Start", "End");

                    b.ToTable("CalendarEventInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
